const data = {
  projects: [
    {
      title: "Expungement Petition Generator",
      siteLink: "https://www.plsephilly.org/",
      codeLink: "",
      imagePath: "./assets/images/projects/plse-expungement.png",
      description: "",
      altText: "Screenshot of the Expungement Petition Generator",
      public: false,
      lastUpdated: Date.parse("02 Nov 2022"),
    },
    {
      title: "Bike Camping PHL",
      siteLink: "./bike_camping_PHL/index.html",
      codeLink:
        "https://github.com/travissouthard/travissouthard.github.io/tree/master/bike_camping_PHL",
      imagePath: "./assets/images/projects/bike_camping_phl.png",
      description: "",
      altText: "Screenshot of my Bike Camping PHL checklist app.",
      public: true,
      lastUpdated: Date.parse("01 Jul 2020"),
    },
    {
      title: "Debt Snowball Calculator",
      siteLink: "./snowball/index.html",
      codeLink:
        "https://github.com/travissouthard/travissouthard.github.io/tree/master/snowball",
      imagePath: "./assets/images/projects/debt-snowball.png",
      description: "",
      altText: "Screenshot of my debt snowball calculator app.",
      public: true,
      lastUpdated: Date.parse("13 Jan 2023"),
    },
    {
      title: "Minesweeper Clone",
      siteLink: "./games/minesweeper/index.html",
      codeLink:
        "https://github.com/travissouthard/travissouthard.github.io/tree/master/games/minesweeper",
      imagePath: "./assets/images/projects/minesweeper.png",
      description: "",
      altText: "Screenshot of my Minesweeper game.",
      public: true,
      lastUpdated: Date.parse("30 Aug 2020"),
    },
    {
      title: "Gravity Play",
      siteLink: "https://editor.p5js.org/travissouthard/full/Fq_vEfA8O",
      codeLink: "https://editor.p5js.org/travissouthard/sketches/Fq_vEfA8O",
      imagePath: "./assets/images/projects/gravity-play.png",
      description: "",
      altText:
        "Screenshot of small colorful planets orbiting each other in a gravity simulation.",
      public: true,
      lastUpdated: Date.parse("16 Jan 2021"),
    },
  ],
  pixelArt: [
    {
      title: "1-Bit Beach Scene",
      siteLink: "https://mastodon.social/@tsouthard/109934647644450793",
      imagePath: "./assets/images/pixelart/beach.png",
      description: "",
      altText:
        "A 1-bit, low-res pixel art image of an outlet pipe and it protective beams on a beach",
      public: true,
      lastUpdated: Date.parse("26 Feb 2023"),
    },
    {
      title: "CRT Flower",
      siteLink: "https://mastodon.social/@tsouthard/109411109868393841",
      imagePath: "./assets/images/pixelart/crt-flower.png",
      description: "",
      altText:
        "A low-color pixel art image of a potted flowering plant growing inside of an empty CRT TV",
      public: true,
      lastUpdated: Date.parse("6 Nov 2022"),
    },
    {
      title: "32x32 Self Portrait",
      siteLink: "https://mastodon.social/@tsouthard/109931960684000706",
      imagePath: "./assets/images/pixelart/headshot-32.png",
      description: "",
      altText: "A low-color low-res pixel art portait of a man with a mustache",
      public: true,
      lastUpdated: Date.parse("26 Feb 2023"),
    },
    {
      title: "House Portrait",
      siteLink: "https://mastodon.social/@tsouthard/109485424439372092",
      imagePath: "./assets/images/pixelart/house.png",
      description: "",
      altText: "A 4-color grayscale pixelart image of a rowhome",
      public: true,
      lastUpdated: Date.parse("30 Oct 2022"),
    },
    {
      title: "1-bit Mushroom",
      siteLink: "https://mastodon.social/@tsouthard/110129547262579634",
      imagePath: "./assets/images/pixelart/mushroom.png",
      description: "",
      altText: "A 1-bit pixelart closeup image of a whitecap mushroom",
      public: true,
      lastUpdated: Date.parse("10 Oct 2022"),
    },
    {
      title: "1-bit Self Portrait",
      siteLink: "https://mastodon.social/@tsouthard",
      imagePath: "./assets/images/pixelart/pixel-art-portrait.png",
      description: "",
      altText: "A 1-bit pixelart self portrait of a man using a keyboard",
      public: true,
      lastUpdated: Date.parse("16 Oct 2022"),
    },
  ],
  blogs: [],
};
